Fiveth requirement
dareddov/recruitment-web-app pull request #5
Opened 2017-03-24 23:40 UTC by dareddov

2017-03-26 18:33 UTC, Exelord requested changes

2017-03-26 18:33 UTC, Exelord commented on app/controllers/admin/users_controller.rb
> +    user.password = 'secret'
Are you serious? :D Why??

2017-03-26 18:33 UTC, Exelord commented
Please, add a description with the test instruction.

2017-03-26 19:11 UTC, dareddov commented on app/controllers/admin/users_controller.rb
> +    user.password = 'secret'
What do you mean? Should i use service for creating new user?

2017-03-26 20:30 UTC, Exelord commented on app/controllers/admin/users_controller.rb
> +    user.password = 'secret'
Why the password is always `secret`? You can use a random stirng generator or just allow user to specific one

2017-03-26 20:35 UTC, dareddov commented on app/controllers/admin/users_controller.rb
> +    user.password = 'secret'
"[...] New users created by admin should have a password set to "secret". [...]"

2017-03-27 17:44 UTC, Exelord commented on app/controllers/admin/users_controller.rb
> +    user.password = 'secret'
Great! Can you see now, what missing in this PR is? :)
Please, always add a PR's description to describe what exactly has been done. If the code and commits are not a self explonatory it's harde to get it from context without the informations and test scenario.

2017-04-03 21:18 UTC, dareddov commented
@Exelord I updated PR, please see at this now, thanks. :)

2017-04-04 19:37 UTC, merged