Sixth requirement
dareddov/recruitment-web-app pull request #6
Opened 2017-03-28 16:14 UTC by dareddov

The admin panel display (under title header) a number which shows the amount of points of interests in the system of "health" type, chosen by women aged between 20 and 30, and the names of PoIs start with "cosm".

2017-04-04 19:46 UTC, Exelord requested changes

2017-04-04 19:46 UTC, Exelord commented on app/models/interest.rb
> +  scope :specific_scope, -> { health_type.joins(:user).where(user_id: User.young_women.select(:id)).where('name like ?', 'cosm%') }
OK :) ... Let's see how you can improve it ;)
Tip: Lot of unnecessary methods

2017-04-04 19:46 UTC, Exelord commented on app/models/user.rb
> +  scope :young_women, -> { where('age between ? and ? and gender = ?', 20, 30, 1) }
'1'? I know that this is women but someone else, no :) Could you use enum value here?

2017-04-04 19:57 UTC, Exelord commented
I reviewed all PR's. Now I wait for tests for all points (all behaviors) and rubocop :)

2017-04-05 21:25 UTC, dareddov commented
@Exelord I improve scopes, look for it not. Thanks. :)

2017-08-21 20:39 UTC, merged